apiVersion: v1
kind: Service
metadata:
  name: myapp-np-service
  labels:
  app: django-api-nextjs-webapp
spec:
  selector:
    app: django-api-nextjs-webapp
    type: NodePort
  ports:
  - nodePort: 
    port: 3000
    targetPort: 3000
