apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-api-nextjs-webapp
  template:
    metadata:
      labels:
        app: django-api-nextjs-webapp
    spec:
      containers:
      - name: django-api-nextjs-webapp
        image: reshma164/django-api-next.js-webapp:latest 
        ports:
        - containerPort: 3000
