name: CI/CD Pipeline

on:
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker build -t ${{ secrets.DOCKER_USERNAME }}/django-api-nextjs-webapp:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/django-api-nextjs-webapp:latest

      - name: Set up Kubernetes Context
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > ~/.kube/config
          kubectl config use-context default

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f kubernetes-deployment.yaml
          
